#
# Copyright (c) 2020 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.
#

name: "Check clang-format"

on: [pull_request]

jobs:
  format:
    name: "Check clang-format"

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: "Checkout fixes branch"
      run: git checkout -b "nfbot/clang-format-fix/${{ github.event.pull_request.head.ref }}"

    - uses: juliangruber/find-pull-request-action@v1
      id: GetPR
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Install clang-format-10"
      run: |
        sudo apt-get update
        sudo apt-get install clang-format-10
    
    - name: "Check source code style"
      run: |
        
        SRC=$(git diff --name-only --diff-filter=d $(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }}) | grep -E ".c$|.h$|.cpp$")

        for changed_file in $SRC; do
          clang-format-10 -style=file -i ${changed_file}
        done

    - name: Check diff
      id: HasDiff
      if: success()
      run: echo "::set-output name=diff::$(git diff --exit-code HEAD)"
    
    - name: Commit changes
      run: |
        git config --global gc.auto 0
        git config --global user.name nfbot
        git config --global user.email nanoframework@outlook.com
        git config --global core.autocrlf true
        
        git add -A
        git commit -m "Automated code style fixes."

    - name: Create Pull Request
      if: success() && steps.HasDiff.outputs.diff
      uses: repo-sync/pull-request@v2
      env:
        PULL_REQUEST_BODY: "Automated fix of code style using project clang-format rules."
        PULL_REQUEST_TITLE: "Fix code style for ${{ github.repository }}/${{ steps.GetPR.outputs.number }}"
        PULL_REQUEST_ASSIGNEES: "${{ github.actor }}"
        PULL_REQUEST_BRANCH: "nfbot/clang-format-fix/${{ github.event.pull_request.head.ref }}"
        PULL_REQUEST_FROM_BRANCH: "nfbot/clang-format-fix/${{ github.event.pull_request.head.ref }}"
        BRANCH_PREFIX: "nfbot/"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check outputs
      if: success()
      run: |
        echo "Submitted PR with code style fixes - ${PULL_REQUEST_URL}"
