name: Code linter
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - name: clang-tidy check
      uses: muxee/clang-tidy-action@0.0.1-rc1
      with:
        args: --config= --format-style=file
